server:
  port: 10201
spring:
  main:
    #springcloudgateway 的内部是通过 netty+webflux 实现的
    #webflux 实现和 spring-boot-starter-web 依赖冲突
    web-application-type: reactive
  profiles:
    active: dev
  redis:
    port: 54326
    host: 106.52.64.158
    password: Abc123456
    database: 3
  security:
    oauth2:
      resourceserver:
        jwt:
          #配置RSA的公钥访问地址
          #jwk-set-uri: 'http://localhost:10301/rsa/publicKey'
          issuer-uri: http://localhost:10301
secure:
  ignore:
    #配置白名单路径
    urls:
      - "/actuator/**"
      - "/oauth2/token"
      - "/oauth2/authorize"
      - "/login"
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
