server:
  port: 8079
  servlet:
    session:
      cookie:
        name: s3
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG
security:
  oauth2:
    client:
      client-secret: 123
      client-id: javaboy
      user-authorization-uri: http://localhost:10301/oauth/authorize
      access-token-uri: http://localhost:10301/oauth/token
      user-info-uri: http://localhost:10301/user