server:
  port: 10301
spring:
  profiles:
    active: dev
  redis:
    port: 54326
    host: 106.52.64.158
    password: Abc123456
    database: 3
  datasource:
    url: jdbc:mysql://localhost:3306/fan_oauth_temp
    username: root
    password: 123qwe...
  security:
    oauth2:
      # OAuth2 Authorization Server配置
      authserver:
        issuer: http://localhost:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO